# Generated by Django 5.1 on 2024-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars.svg', null=True, upload_to='avatars/'),
        ),
    ]
